### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by mhsjlw** [BenchMine/RakLib#1]
Does this library work as of right now for sending/receiving RakNet datapackets?

**Comment by InusualZ** [comment]
This library is kind of outdated. Since Mojang have reworked some of his network code. But yeah, I think that you can receive/send datapacket. I don't have any documentation of how the library work, but you can check out BenchMine source code to see how do I implement it. The library is very WIP may have some memory leaks and that sort of thing. I don't really recommend you to use this library as it for any server sorftware. But you are free to modify it :)

**Comment by mhsjlw** [comment]
Awesome. Thanks.
